# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dottie < Formula
  desc "A dotfiles manager for macOS and Linux"
  homepage "https://github.com/clutchski/dottie"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.6/dottie_0.1.6_darwin_amd64.tar.gz"
      sha256 "37f4cca1c9d4d66fa475084de28c9eb2647d516c65c8317018bf7a99ffd4e1a1"

      def install
        bin.install "dottie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.6/dottie_0.1.6_darwin_arm64.tar.gz"
      sha256 "f334665a62e702fa5e62d3c1ce3dd18b0c8edb1ad660ee8f5b5a54f08f7e102e"

      def install
        bin.install "dottie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.6/dottie_0.1.6_linux_amd64.tar.gz"
      sha256 "62f26f49ba1d27a8cd15f17917bb72fcc523d5ce144b774678f43815e0bc682b"
      def install
        bin.install "dottie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.6/dottie_0.1.6_linux_arm64.tar.gz"
      sha256 "d6e0b639a7d09d07db8a206ac163db2c91488f2c548efd02ef27511d9d01b024"
      def install
        bin.install "dottie"
      end
    end
  end

  test do
    system "#{bin}/dottie", "version"
  end
end
