# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dottie < Formula
  desc "A dotfiles manager for macOS and Linux"
  homepage "https://github.com/clutchski/dottie"
  version "0.1.9-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.9-beta.1/dottie_0.1.9-beta.1_darwin_amd64.tar.gz"
      sha256 "f71b8f0091c30b86620d1f5f692324fafe740e6abd2fe74503383da16fb3dc1e"

      def install
        bin.install "dottie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.9-beta.1/dottie_0.1.9-beta.1_darwin_arm64.tar.gz"
      sha256 "e47c0ebe76f1651f42e492c0050149757a017901ff0bf5c5117e098cbc1615a8"

      def install
        bin.install "dottie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.9-beta.1/dottie_0.1.9-beta.1_linux_amd64.tar.gz"
      sha256 "2f4cf0097e82955bcf126f691eaf50bd358dd936ecc65a6881b54b05826b545a"
      def install
        bin.install "dottie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.9-beta.1/dottie_0.1.9-beta.1_linux_arm64.tar.gz"
      sha256 "116ef33bb572f7e7deecc5fed819523570cb422bc3a917ea1090a1c46ae76054"
      def install
        bin.install "dottie"
      end
    end
  end

  test do
    system "#{bin}/dottie", "version"
  end
end
