# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dottie < Formula
  desc "A dotfiles manager for macOS and Linux"
  homepage "https://github.com/clutchski/dottie"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.5/dottie_0.1.5_darwin_amd64.tar.gz"
      sha256 "06b9237de1290c82f476230980d7d428b995f1196b6019fc96ce55c64dd931c5"

      def install
        bin.install "dottie"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.5/dottie_0.1.5_darwin_arm64.tar.gz"
      sha256 "bf261dc0db76012586f227572b129124c17a054e366ba0171a53d10d7d1a2205"

      def install
        bin.install "dottie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.5/dottie_0.1.5_linux_amd64.tar.gz"
      sha256 "e1e2e5b4a7a936b953ee96b21b6c37b20ca4f28f2cb1836706266004b1f7df88"
      def install
        bin.install "dottie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clutchski/dottie/releases/download/v0.1.5/dottie_0.1.5_linux_arm64.tar.gz"
      sha256 "1224baba93b5dabd1cbcdb301a3124e737a02d8c55b66c6dc909f5671dcf6e07"
      def install
        bin.install "dottie"
      end
    end
  end

  test do
    system "#{bin}/dottie", "version"
  end
end
